version: 2

sources:
  - name: warehouse
    database: warehouse
    tables:
      - name: basic_info
      - name: daily_prices
      - name: fundamentals
      - name: holders
      - name: upgrades_downgrades
